// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdmykaeplmizrzklxsui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kbXlrYWVwbG1penJ6a2x4c3VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDIxNjEsImV4cCI6MjA3MzkxODE2MX0.cxvdLVTxUyCle-UkIgTRcFUhdhEwt0NZICHU84qJQUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});